use_frameworks!

platform :ios, '8.0'

target 'FuYTKNetwork_Example' do
  pod 'FuYTKNetwork', :path => '../'

  target 'FuYTKNetwork_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
